
[package]
name = "osmium"
version = "0.1.0"
authors = ["Matthias Debernardini <m.f.debern@protonmail.com>"]
description = "BIP-85 - deterministic entropy from bip32 keychains"
readme = "README.md"
license = "MIT"
edition = "2021"

[dependencies]
bitcoin = "0.28.1"
bip39 = { version = "1.0.1", optional = true}
csv = "1.1.6"
chrono = "0.4.19"
thiserror = "1.0.30"
anyhow = "1.0.56"
clap = { version = "3.1.6", features = ["derive", "cargo"] }
log = "0.4.0"
fern = "0.6.1"
age = "0.8.0"
derive_more = "0.99.17"
config = { version = "0.13.1", features = ["toml"] }
bip85 = "0.1.1"
bdk = { version = "0.18.0", features = ["bip39", "keys-bip39"] }
rand = "0.8.5"
rand_core = "0.6.3"

[profile.dev]
opt-level = 0
[profile.release]
opt-level = 3

